### ISSUE TITLE
Precompiled app?

### ISSUE THREAD

**Issue by gedaiu** [inversepath/interlock#14]
There are any precompiled binaries for this project?

**Comment by abarisani** [comment]
Not at this time, we are encouraging users to compile their own for now.

**Comment by gedaiu** [comment]
It would be nice then to have a cookbook about how we can compile it on a comuter... not everyone knows that...

**Comment by abarisani** [comment]
The README file is quite clear about compilation instructions, we only avoid specifying how to install Go but there are plenty of resources to learn how to do that and chances are that your Linux distribution already has a Go >= 1.4 package ready. If you have troubles compiling it just email me directly and I will be happy to provide support.

**Comment by abarisani** [comment]
You might be happy to know that we just started publishing releases at:

https://github.com/inversepath/interlock/releases

Cheers

**Comment by gedaiu** [comment]
awesome! thanks!
