### ISSUE TITLE
Suggestion for TextSecure usability improvement.

### ISSUE THREAD

**Issue by azman0101** [inversepath/interlock#18]
Hi,

I wish to thank you for all you've done ! I would humbly like to suggest an improvement of TextSecure UI.

I wish to create small chat box for notifying of new messages and then engaged in conversation.

Can you give some tips on how to build this functionality in a modular manner ?

Regards.

**Comment by abarisani** [comment]
Thanks for the suggestion! We are aware of potential UI improvements and we have a background task on improving them. We are actually evaluating incorporating the excellent Signal Desktop (currently in beta) UI directly if we can find some good code separation that we can leverage on, between their UI and application code.

I'll leave it to my colleague Daniele to follow up and understand if it makes sense to improve the current UI, as you suggest, or if waiting for a more complete rehaul makes more sense.

**Comment by danbia** [comment]
Hi,
as mentioned by my colleague  Andrea we are currently evaluating the integration with the Signal Desktop UI. This UI provides among other features exactly the same functionality you are describing: a pop-up appears every time a new msg has been received and by clicking on it you can engage the conversation. Thus, I would advice to wait the integration of Signal Desktop if this feature is not extremely urgent for you.

Cheers,
Daniele

**Comment by abarisani** [comment]
Integration of Signal Desktop has been re-evaluated as not being a priority, recent usability improvements in safety numbers verification and registration go towards this goal. We will gradually increase usability of the feature in relation to user feedback but for now I think we have a good compromise and I'd like to close the issue in the meantime.

Thanks!
