### ISSUE TITLE
Armory External Storage

### ISSUE THREAD

**Issue by PowerPress** [inversepath/interlock#19]
Is it possible to add additional external storage to the armory for example a large 4 TB hard drive to use as a secure encryption/decryption system similar to encrypted SSD drives but all completely open source?

**Comment by abarisani** [comment]
These questions are better suited for our [support mailing list](https://groups.google.com/forum/#!forum/usbarmory) as they are not code issues.

To answer your question, when switching the USB armory in host mode and using the related [adapter](https://github.com/inversepath/usbarmory/wiki/Host-adapter) you can attach any external USB device you want. This would be the only way to add external storage, other than the microSD card of course.
