### ISSUE TITLE
USB Armory INTERLOCK raw image does not work with Windows 10

### ISSUE THREAD

**Issue by alexurbanowicz** [inversepath/interlock#23]
The Armory with default INTERLOCK image is detected on Windows 10 as Serial USB device. This is the issue discussed on the mailing list here: https://groups.google.com/forum/#!topic/usbarmory/bFZBrTKq2Mg but it involves the INTERLOCK image v2016.10.24 and not the Debian image.

**Comment by abarisani** [comment]
Have you installed the drivers as indicated in our wiki? (https://github.com/inversepath/usbarmory/wiki/Host-communication#setup--connection-sharing-windows-7-8-10)

**Comment by gh0stshell** [comment]
on Win10 and works just fine, cannot get logged ATM

**Comment by abarisani** [comment]
For driver issues this thread helps: https://groups.google.com/forum/#!topic/usbarmory/bFZBrTKq2Mg

For inability to log please ensure that you are using the correct INTERLOCK credentials, if you have issues please contact our support email directly.

Thanks
