### ISSUE TITLE
Change Default Interlock Port

### ISSUE THREAD

**Issue by gh0stshell** [inversepath/interlock#26]
How do I get to the file to change

 "bind_address": "0.0.0.0:4430",

SSH? If so whats the default login?

If not do I just put the card in my computer and can see the conf file?

Is this the correct conf file /etc/interlock/interlock.conf ?

**Comment by danbia** [comment]
@gh0stshell, assuming that you are using the embedded Interlock distribution you can access the USB armory via SSH (using the interlock user) uploading a .ssh/authorized_keys file via the interlock web interface as detailed in [https://github.com/inversepath/usbarmory/blob/master/software/buildroot/README-INTERLOCK.md](https://github.com/inversepath/usbarmory/blob/master/software/buildroot/README-INTERLOCK.md),
the configuration file is placed under /etc/interlock/interlock.conf.

Unfortunately, changes to the configuration file in the USB armory embedded Interlock distribution will not be persistent across reboots.

If you need to access via SSH the USB armory and modify persistently the Interlock configuration I advice to use one of the supported distributions [https://github.com/inversepath/usbarmory/wiki/Available-images](https://github.com/inversepath/usbarmory/wiki/Available-images) and install the Interlock application following the documentation [https://github.com/inversepath/interlock](https://github.com/inversepath/interlock), or alternatively recompile the embedded Interlock distribution using buildroot [https://github.com/inversepath/usbarmory/blob/master/software/buildroot/README-INTERLOCK.md#compiling](https://github.com/inversepath/usbarmory/blob/master/software/buildroot/README-INTERLOCK.md#compiling) and modifying the file profiles/interlock/overlay/etc/interlock.conf according to your needs.
