### ISSUE TITLE
Signal Support - Manual Build

### ISSUE THREAD

**Issue by gh0stshell** [inversepath/interlock#29]
Is this the error you mentioned would happen when building with signal support?

./signal.go:146: undefined: strings.Compare

Is there anyway to fix this so I can build interlock with signal support?

**Comment by abarisani** [comment]
What is your Go version? (type `go version` to find out)

**Comment by gh0stshell** [comment]
1.4.3, had issues with 1.5 and 1.6.2 just building with no signal support

**Comment by abarisani** [comment]
I use go 1.7.4 and I can build without issues, kindly update to the latest stable Go version and show the error that you get while compiling.

I would recommend the following to install all dependencies automatically:

go get -u github.com/janimo/textsecure/cmd/textsecure
go get -u -tags signal github.com/inversepath/interlock/cmd/interlock

**Comment by gh0stshell** [comment]
I wiped the card and have been waiting for your response before I try again, I will start the setup right now and let you know what happens

**Comment by gh0stshell** [comment]
FYI i can run

go get -u github.com/janimo/textsecure/cmd/textsecure

without issues, I only get the error listed in the first post when using "make with_signal" after pulling the 

https://github.com/inversepath/interlock/

repo and issuing init and update on the submodules

**Comment by gh0stshell** [comment]
after I run 

go get -u github.com/janimo/textsecure/cmd/textsecure
go get -u -tags signal github.com/inversepath/interlock/cmd/interlock

do I need to do anything else or is interlock now setup with signal support?

**Comment by gh0stshell** [comment]
tweaked my steps and with 1.7.4 everything built successfully. During making the usb armory interlock manually I created a step by step guide to help others, you can post it if you would like to 

http://support.jpgottech.com/knowledgebase.php?article=92

**Comment by gh0stshell** [comment]
Now that I was able to compile interlock with signal support successfully, how did you make it auto run when the armory is booted?

**Comment by gh0stshell** [comment]
Why is the manual make_signal binary 6MB and the go auto download & compile 9.4MB??

**Comment by abarisani** [comment]
Here's an example systemd configuration to run INTERLOCK at boot: 
https://github.com/inversepath/interlock/wiki#example-systemd-unit-configuration

(you would have to move/install files accordingly)

The Makefile strips the binary, the go get probably doesn't, hence the size difference.
