### ISSUE TITLE
Error On Newly Compiled Interlock

### ISSUE THREAD

**Issue by gh0stshell** [inversepath/interlock#30]
I get the following when trying to start interlock using a conf file

invalid path for static files

I get no info on what files it is talking about other then

2017/01/25 04:34:10 main.go:123: invalid path for static files: stat static: no such file or directory

**Comment by gh0stshell** [comment]
Firgured it out in the code

**Comment by abarisani** [comment]
Please send emails for support requests rather than opening an issue for every single question.

Thanks
