### ISSUE TITLE
Bitcoin/keybase support

### ISSUE THREAD

**Issue by DeveloppSoft** [inversepath/interlock#32]
Hi,
I am here to suggest who some things:
 -  adding a web based bitcoin wallet.
 -  adding keybase chat support which was released very recently (but you already implement signal).
For the bitcoin part I can work on the server side code but I won't be able to work on the web UI (I am a terrible web developer :grin:).
Please tell me what you think about that.

**Comment by abarisani** [comment]
Keybase support was requested in the past but for now we are only committed to Signal and have no plans to add any more.

Concerning bitcoin wallet functionality we think this is out of scope of the tool and is probably better served by existing bitcoin wallets. We would like to avoid code duplication and add too many functionalities, do a few things but do them well ;).

Thanks!
