### ISSUE TITLE
Add file editing feature.

### ISSUE THREAD

**Issue by abarisani** [inversepath/interlock#33]
Now that INTERLOCK allows creation of new files, by editing their contents, it seems useful to add the possibility of editing existing files (maybe locking it down just to text files?).

**Comment by DeveloppSoft** [comment]
If you just want a basic editor, [react-rte](https://github.com/sstur/react-rte) might be interesting.
On the other hand, if you want to add a richer editor [code mirror](https://codemirror.net) is worth a look.
Of course, they are only suggestions :smile:.

**Comment by hteso** [comment]
Even the same "new file" dialog currently in use would be great to perform simple editing tasks :)

**Comment by abarisani** [comment]
Yes, when this will be implemented it will leverage on that. No plans to pull in rich third party editors.

**Comment by abarisani** [comment]
Closed due to inactivity/lack of interest.
