### ISSUE TITLE
File Fingerprinting [Feature Request]

### ISSUE THREAD

**Issue by nathanph** [inversepath/interlock#35]
It would be nice to have fingerprinting functionality to ensure file integrity.

With a collection of common fingerprinting hash functions:
* MD5
* SHA*
* Etc.

**Comment by abarisani** [comment]
I've prepared the API to support this in the UI, for now with SHA256 support only:

https://github.com/inversepath/interlock/commit/da8c565d518da3db989b4566b6142683062be2e8

**Comment by danbia** [comment]
Feature added on commit 00a7c086e9194cd3c122a30b241ef80c42a7a774
