### ISSUE TITLE
Attempting to use a path deeper than one level results in error

### ISSUE THREAD

**Issue by Foleychris** [inversepath/interlock#36]
**Steps to Reproduce**

1. Import a TOTP key
2. Click to enter the 'keys' directory
3. Click to enter the 'totp' directory
4. Receive error "INTERLOCK error - path traversal detected"

OR

1. Create directory 'a'
2. Enter 'a'
3. Attempt to create directory 'b'
4. Receive error "path traversal detected"

**Build info**
Prebuilt binary, interlock-arm-v2017.08.03.

**Config**
````
{
  "debug": true,
  "static_path": "static",
  "set_time": true,
  "bind_address": "0.0.0.0:80",
  "tls": "off",
  "tls_cert": "certs/cert.pem",
  "tls_key": "certs/key.pem",
  "tls_client_ca": "",
  "hsm": "off",
  "key_path": "keys",
  "volume_group": "lvmvolume",
  "ciphers": [
          "OpenPGP",
          "AES-256-OFB",
          "TOTP"
  ]
}
````

**Comment by Foleychris** [comment]
Possibly related to https://github.com/inversepath/interlock/commit/c6c5044b49086b7cd68acebed44e69f94b6bdd07#diff-bd2d0b55fe13aec5a7f6becc2755e9a3L55 ? Will attempt to revert this and build.

**Comment by Foleychris** [comment]
Git bisect'ing through, it looks like it was introduced in https://github.com/inversepath/interlock/commit/c6c5044b49086b7cd68acebed44e69f94b6bdd07

**Comment by abarisani** [comment]
Please test be2f8cdea2f01c13793592ffff3cb8b6781ab35c

It should fixe the issue.

Sorry for this!

**Comment by Foleychris** [comment]
Worked great, thank you!
