### ISSUE TITLE
cannot connect to my usbarmory

### ISSUE THREAD

**Issue by mosesBD123** [inversepath/interlock#39]
i used the binary files for interlock (interlock-usbarmory-v2018.01.09.tar.xz) and configured a bootable microSD using the raw file 
when i connect the usbarmory to my PC (running windows 10) it creates an Ethernet adapter and gives me an ip address (10.0.0.2).
i can ping 10.0.0.1 which i think is the usbarmory but i cant login via SSH (using usbarmory as user and pass) or connect to https://10.0.0.1 
any ideas?

**Comment by mosesBD123** [comment]
i can access web interface of interlock via https://10.0.0.1:4430 however the SSH problem still persists also when i open the web interface it is asking me to enter a volume name and password 
i read the documents and realized that i should create an encrypted volume
i tried creating one by the guide in interlock docs (using pvcreate and ...) but i couldnt do it
does anybody know of a more straightforward tool for me to create encrypted volumes with?

**Comment by mosesBD123** [comment]
i also tried using the key.pem file generated in interloc-certs dir with  the following command 
ssh -i key,pem interlock@10.0.0.1 and got the following error
Permission denied (publickey).

**Comment by mosesBD123** [comment]
apparently i did not fully understand the behavior described in 
https://github.com/inversepath/usbarmory/blob/master/software/buildroot/README-INTERLOCK.md
i managed to get access

**Comment by samuelclk** [comment]
Hi @mosesBD123 i just got my USB Armory MK II device and used "dd" to get the pre-built interlock binaries into my microSD card. However I cannot access 10.0.0.1:4430 via my web browser and am wondering if you could point me in the right direction.

Some additional info:
1) My LED light blinks twice when i plug it in and then stops flashing (just stays on constantly) at the 3rd blink
2) I am able to ping 10.0.0.1 from my terminal
3) I am unable to ssh into 10.0.0.1 and it says i need a private key to access it
