### ISSUE TITLE
Cannot select file or directory in firefox.

### ISSUE THREAD

**Issue by vloup** [inversepath/interlock#42]
Hello,

I have tested interlock on both Chromium and Firefox, and everything behaves as expected in chromium.
But with Firefox (Linux, running version 67.0.2 currently), it is another story: I cannot select anything, and thus I cannot move in any directory (without doing some hackery stuffs).
I've tested with a clean browser profile on a second machine (same Linux distribution), and the problem persists.
It used to work in the past, so something likely got changed in Firefox and broke something here.

What I am observing is that the click event in `file_manager.js` line 378 is never triggered, even if I confirm that the `addClass` statement right before is correctly executed. I can see that click events do work since the one in line 71 and line 344 seem to be called.

In the HTML code, this gets expressed as elements never get in a `ui-selected` state. It does not get beyond a `ui-selecting` state. I can observe that `Interlock.UI.doubleClick` is always false even if I try to set a huge `Interlock.UI.doubleClickDelay` value.

Currently, the ways I was able to force a chdir was to either edit the sessionStore by hand and refresh the page, force `ui-selected` in the HTML and double click again on the item, or, well, use chromium instead.

**Comment by danbia** [comment]
Fixed in commit: f43e8af9e1ad81b2af95143f12618f03a54c1f74.

Thank you very much for your report.
