### ISSUE TITLE
Cannot compile code

### ISSUE THREAD

**Issue by iad42** [inversepath/interlock#9]
Cannot compile the program, getting this error on syscall module.

~/github/interlock$ make

cd server && go build -ldflags "-X main.InterlockBuild \"<name>@mac.local on <date>\"" -o ../interlock
 # _/Users/123/github/interlock/server
./status.go:118: undefined: syscall.Sysinfo_t
./status.go:119: undefined: syscall.Sysinfo
make: *** [build] Error 2

Have read that syscall package moved to sys.unix, but cannot successefully import this package. Using MacOS Yosemite.

**Comment by abarisani** [comment]
I am afraid that INTERLOCK is designed for Linux at this time and it can only be compiled, or cross-compiled, from Linux hosts. I'll update docs to make this clearer.
